spring:
    config:
        import: optional:classpath:global-props.yml
    application:
        name: ms-app-services
    jpa:
        properties:
            hibernate:
                default_schema: secure_on_movil


server:
    port: 8091
    

logging:
    level:
        com.secureon.appmovil: DEBUG
        org.springframework.security: DEBUG