spring:
    config:
        import: optional:classpath:global-props.yml
    application:
        name: ms-api-gateway
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Transfer-Encoding, RETAIN_FIRST
server:
    port: 8090


api-gateway:
    security:
        estrategy: none
        paths-habilitados: /ws/internal/**,/ws/secure-on/**,/api/secure-on/seguridad/v1/**,/api/secure-on/servicios-moviles/v1/**,/api/secure-on/centro-de-monitoreo/v1/**       
    config:
        gateway-paths:
            app-movil: /servicios-moviles
            cmd-control: /centro-de-monitoreo
            seguridad: /seguridad
        services-paths:
            app-movil: /api/app-movil
            cmd-control: /api/cdm-control
            seguridad: /api/seguridad
        services-urls:
            app-movil: http://localhost:8091
            cmd-control: http://localhost:8092
            seguridad: http://localhost:8093
        cors:
            allowed-origins: "*"
            allowed-methods: GET,POST,PUT,DELETE,OPTIONS
            allowed-headers: Content-Type,Authorization
            allow-credentials: false
        prefix-api: /api/secure-on
        prefix-ws: /ws/secure-on
        
logging:
    level:
        com.secureon.apigateway: DEBUG