spring:
    config:
        import: optional:classpath:global-props.yml
    application:
        name: ms-cdm-control
    jpa:
        properties:
            hibernate:        
                default_schema: secure_on_cdmso        

server:
    port: 8092

logging:
    level:
        com.secureon.cdmcontrol: DEBUG
        org.springframework.security: DEBUG