spring:
    config:
        import: optional:classpath:global-props.yml
    application:
        name: ms-seguridad
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                default_schema: secure_on_movil
                jdbc:
                    lob:
                        non_contextual_creation: true
        open-in-view: false
    mail:
        host: smtp.ethereal.email
        port: 587
        username: wendell.wolff@ethereal.email
        password: w4k2eUSgNmWXdQMGrk
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000

server:
    port: 8093


app:
    audit:
        enabled: true
    role:
        usuario: "USUARIO"
        admin: "ADMIN_CDM"
        operador: "OPERADOR_CDM"
        prefijo: "ROLE_"
    code-expiration:
        mail: 600 # 10 minutos en segundos
        sms: 120 # 2 minutos en segundos

logging:
    level:
        com.secureon.seguridad: DEBUG
        org.springframework.security: DEBUG